name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Debug token availability
        run: |
          echo "Token name: PKG_TOKEN"
          echo "Token preview: ${PKG_TOKEN:0:10}..." # Mostrar primeros 10 chars
          echo "Repository: $GITHUB_REPOSITORY"

      - name: Build and Deploy with PKG_TOKEN
        run: mvn -B clean deploy -Dgithub.actor=AtlasFreight
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}  # ✅ Usando PKG_TOKEN
          PKG_TOKEN: ${{ secrets.PKG_TOKEN }}     # ✅ Variable adicional por si acaso

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Check packages at: https://github.com/AtlasFreight/response_wrapper/packages"